### ISSUE TITLE
Proposal: improve loading from a directory, add special support for index.* files

### ISSUE THREAD

**Issue by brain4711** [cutsin/require-yml#13]
Hi folks! It's great to have this library but I encountered a use-case that propably requires some changes to the source-code.
## Use-case:
As a configuration provider, 
I want to split a large configuration across separate files 
and be able to load and merge all files by requiring the parent folder.

So far this is already implemented, but let's consider the following scenario:

I have a [json schema definition](https://json-schema.org/) with some properties and examples:
``` yaml
# file:///entities/door/door.schema.yml
description: The door schema.
type: object
examples:
-   name: A green door
    opened: false
-   name: A red door
    opened: true
properties:
    name:
        default: ''
        type: string
    opened:
        default: false
      type: boolean
```
With this i can easily require the schema with `const doorSchema = req('entities/door/door.schema')`
But as this schema definition grows during development, at some point you might consider to split this schema by extracting the 'examples' section to a separate file. My approach would be to organize it like this:
```
entities/
    |- door/
        |- door.schema/
            |- index.yml
            |- examples.yml
```
where the _index.yml_ file contains the base schema definition (description, properties, type ...) and _./examples.yml_ contains all the 'examples'.

I still want to be able to load the whole schema with `const doorSchema = req('entities/door/door.schema')`
The current implementation of the directory-import feature would add the content of the _index.yml_ file to the 'index' property key but I want it to be merged into the root object directly.

The way I see it, it is not possible with the current implementation, or am I missing something?
